
networks:
  minhaAppNetwork:
 
services: 
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Numsey#2024
  
    blazorsqlserver:
        container_name: BlazorContainer
        image: ${DOCKKER_REGISTRY-}blazordockerdemo
        ports: 
            - 8001:8080
        build:
            context: .
            dockerfile: BlazorSQLServer/Dockerfile
        depends_on:
            - SqlServerDb
            
       